### ISSUE TITLE
Can those metrics be used for sample rates other than 24kHz?

### ISSUE THREAD

**Issue by seungwonpark** [mbinkowski/DeepSpeechDistances#1]
Hi, Mikolaj
Thanks for open-sourcing those metrics, and congratulations on ICLR acceptance of your paper!

I wonder if those metrics could be also used for speech with sample rates other than 24kHz. Since 22050Hz is also popular for speech synthesis, I'm thinking of using those metrics by resampling the speech from 22050Hz to 24000Hz using `ffmpeg`. Will that be okay?

Looking forward for your reply, thanks in advance.
Seungwon

**Comment by seungwonpark** [comment]
Through my inspection, it looks like the audio is resampled to 16kHz audio and then converted to a spectrogram with n_fft=window=320, hop=160. 

I suspect that all audios with sample rate higher than 16kHz will be okay here.

**Comment by mbinkowski** [comment]
Hi Seungwon, indeed we resample to 16kHz as that's the frequency at which DeepSpeech2 operates (i.e. it is trained on spectrograms obtained at such frequency). Both higher and lower rates would be fine, as long as both compared samples use the same one, otherwise different artifacts from resampling may affect the result.
Thanks and good luck.

**Comment by seungwonpark** [comment]
Thank you very much for your response, Mikolaj. Now I've got things clear.
